# Generated by Django 3.0 on 2021-11-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0006_auto_20211129_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
