# Generated by Django 3.0 on 2021-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0008_auto_20211130_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediants',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
