# Generated by Django 3.0 on 2021-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0009_auto_20211130_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='direction',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingrediants',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
