# Generated by Django 3.0 on 2021-12-02 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0013_auto_20211202_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
